# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Title
#'
#' Description
#'
#' @param x An integer vector
#' @useDynLib LeesApprox
#' @export
linear_int <- function(x, y, xout) {
    .Call('_LeesApprox_linear_int', PACKAGE = 'LeesApprox', x, y, xout)
}

calcprob <- function(x, y, xout, LenBins) {
    .Call('_LeesApprox_calcprob', PACKAGE = 'LeesApprox', x, y, xout, LenBins)
}

myseq_by <- function(x, y, by) {
    .Call('_LeesApprox_myseq_by', PACKAGE = 'LeesApprox', x, y, by)
}

#' Title
#'
#' Description
#'
#' @param x An integer vector
#' @useDynLib LeesApprox
#' @export
myseq_len <- function(start, end, length) {
    .Call('_LeesApprox_myseq_len', PACKAGE = 'LeesApprox', start, end, length)
}

#' Title
#'
#' Description
#'
#' @param x An integer vector
#' @export
LeesApprox <- function(FVec, ngtg, maxsd, binwidth, M, Linf, K, t0, LFS, L5, Vmaxlen, LinfCV, maxage) {
    .Call('_LeesApprox_LeesApprox', PACKAGE = 'LeesApprox', FVec, ngtg, maxsd, binwidth, M, Linf, K, t0, LFS, L5, Vmaxlen, LinfCV, maxage)
}

