


# Statistical Catch-at-Age with Growth Type Groups (SCA_GTG){.tabset}

## Summary Tables {.tabset}

```{r}
  sx <- summary_SCA_GTG(Assessment)[-1]
  for(i in 1:length(sx)) {
    dat <- as.data.frame(sx[[i]])
    for(j in 1:ncol(dat)) if(nrow(dat) > 0 && is.numeric(dat[, j])) dat[, j] <- ifelse(dat[, j] > 1e3, round(dat[, j], 0), signif(dat[, j], 3))
    sx[[i]] <- dat
  }
```


### Current Status
`r sx[[1]]`

### Input Parameters
`r sx[[2]]`

### Derived Quantities
`r sx[[3]]`

### Model Estimates
`r sx[[4]]`

## Life History

```{r, fig.cap="Mean length-at-age from Data object."}
MSEtool:::plot_generic_at_age(1:info$data$max_age, info$LH$mean_LAA, label = "Mean Length-at-age")
```

```{r, fig.cap="Mean weight-at-age from Data object."}
MSEtool:::plot_generic_at_age(1:info$data$max_age, info$LH$mean_WAA, label = "Mean Weight-at-age")
```

```{r, fig.cap="Length-weight relationship."}
plot(info$LH$mean_LAA, info$LH$mean_WAA, typ = "o", xlab = "Length", ylab = "Weight")
abline(h = 0, col = "grey")
```

```{r, fig.cap="Maturity at age. Length-based maturity parameters were converted to the corresponding ages."}
plot_generic_at_age(1:info$data$max_age, info$data$mat, label = "Maturity")
 ```

## Data

```{r, fig.cap="Catch time series."}
plot_timeseries(as.numeric(names(Obs_Catch)), Obs_Catch, label = "Catch")
```

```{r, fig.cap="Index time series."}
plot_timeseries(as.numeric(names(Obs_Index)), Obs_Index, label = "Index")
```

```{r, fig.cap="Age composition bubble plot."}
if(any(info$data$CAA_n > 0)) {
  ind_valid <- rowSums(Obs_C_at_age, na.rm = TRUE) > 0
  plot_composition(info$Year[ind_valid], Obs_C_at_age[ind_valid, ], ages = NULL, plot_type = "bubble_data",
                   annual_yscale = "proportions", annual_ylab = "Frequency")
}
```

```{r, fig.cap="Annual age compositions."}
if(any(info$data$CAA_n > 0)) {
  ind_valid <- rowSums(Obs_C_at_age, na.rm = TRUE) > 0
  plot_composition(info$Year[ind_valid], Obs_C_at_age[ind_valid, ], ages = NULL, plot_type = "annual", annual_yscale = "proportions", annual_ylab = "Frequency")
}
```

```{r, fig.cap="Length composition bubble plot."}
if(any(info$data$CAL_n > 0)) {
  ind_valid <- rowSums(info$data$CAL_hist, na.rm = TRUE) > 0
  plot_composition(info$Year[ind_valid], info$data$CAL_hist[ind_valid, ], CAL_bins = info$data$LenMids, plot_type = "bubble_data", annual_yscale = "proportions", annual_ylab = "Frequency")
}
```

```{r, fig.cap="Length compositions."}
if(any(info$data$CAL_n > 0)) {
  ind_valid <- rowSums(info$data$CAL_hist, na.rm = TRUE) > 0
  plot_composition(info$Year[ind_valid], info$data$CAL_hist[ind_valid, ], CAL_bins = info$data$LenMids, plot_type = "annual",
                 annual_yscale = "proportions", annual_ylab = "Frequency")
}
```


## Assessment {.tabset}
### Estimates and Model Fit

```{r, fig.cap="Estimate of R0, distribution based on normal approximation of estimated covariance matrix."}
if(conv) {
  ind <- names(SD$par.fixed) == "log_R0"
  plot_lognormalvar(SD$par.fixed[ind], sqrt(diag(SD$cov.fixed)[ind]), label = expression(Unfished~~recruitment~~(R[0])), logtransform = TRUE)
}
```

```{r, fig.cap="Estimate of steepness, distribution based on normal approximation of estimated covariance matrix."}
if(conv && !"transformed_h" %in% names(obj$env$map)) {
  ind <- names(SD$par.fixed) == "transformed_h"
  plot_steepness(SD$par.fixed[ind], sqrt(diag(SD$cov.fixed)[ind]), is_transform = TRUE, SR = info$data$SR_type)
}
```

```{r, fig.cap="Estimated selectivity at length."}
plot(info$data$LenMids, TMB_report$Select_at_length, xlab = "Length", ylab = "Selectivity", typ = 'n', ylim = c(0, 1.1))
abline(h = 0, col = 'grey')
lines(info$data$LenMids, TMB_report$Select_at_length, typ = 'o')
```

```{r, fig.cap="Annual selectivity at age."}
plot_composition(info$Year, Selectivity, plot_type = "annual", ages = 1:info$data$max_age, annual_yscale = "raw", annual_ylab = "Selectivity")
```

```{r, fig.cap="Observed (black) and predicted (red) index."}
plot_timeseries(as.numeric(names(Index)), Obs_Index, Index, label = "Index")
```

```{r, fig.cap="Index residuals in log-space."}
plot_residuals(as.numeric(names(Index)), log(Obs_Index/Index), label = "log( Index ) Residual")
```

```{r, fig.cap="QQ-plot of index residuals in log-space."}
qqnorm(log(Obs_Index/Index), main = "")
qqline(log(Obs_Index/Index))
```

```{r, fig.cap="Observed (black) and predicted (red) catch."}
plot_timeseries(as.numeric(names(Catch)), Obs_Catch, Catch, label = "Catch")
```

```{r, fig.cap="Catch residuals in log-space."}
plot_residuals(as.numeric(names(Catch)), log(Obs_Catch/Catch), label = "log( Catch ) Residual")
```

```{r, fig.cap="QQ-plot of catch residuals in log-space."}
qqnorm(log(Obs_Catch/Catch), main = "")
qqline(log(Obs_Catch/Catch))
```

```{r, fig.cap="Pearson residual bubble plot of age compositions (grey bubbles are negative, white are positive)."}
if(any(info$data$CAA_n > 0)) {
ind_valid <- rowSums(Obs_C_at_age, na.rm = TRUE) > 0
plot_composition(info$Year[ind_valid], Obs_C_at_age[ind_valid, ], C_at_age[ind_valid, ], plot_type = "bubble_data")
}
```

```{r, fig.cap="Annual observed (black) and predicted (red) age compositions."}
if(any(info$data$CAA_n > 0)) {
ind_valid <- rowSums(Obs_C_at_age, na.rm = TRUE) > 0
plot_composition(info$Year[ind_valid], Obs_C_at_age[ind_valid, ], C_at_age[ind_valid, ], plot_type = "annual", ages = NULL, N = info$data$CAA_n[ind_valid])
}
```

```{r, fig.cap="Pearson residual bubble plot of length compositions (grey bubbles are negative, white are positive)."}
if(any(info$data$CAL_n > 0)) {
ind_valid <- rowSums(info$data$CAL_hist, na.rm = TRUE) > 0
plot_composition(info$Year[ind_valid], info$data$CAL_hist[ind_valid, ], TMB_report$CALpred[ind_valid, ], plot_type = "bubble_data")
}
```

```{r, fig.cap="Annual observed (black) and predicted (red) length compositions."}
if(any(info$data$CAL_n > 0)) {
ind_valid <- rowSums(info$data$CAL_hist, na.rm = TRUE) > 0
plot_composition(info$Year[ind_valid], info$data$CAL_hist[ind_valid, ], TMB_report$CALpred[ind_valid, ], plot_type = "annual", ages = NULL, N = info$data$CAA_n[ind_valid])
}
```

```{r, fig.cap="Time series of recruitment deviations. Deviations prior to the first year of the model are in blue."}
plot_residuals(as.numeric(names(Dev)), Dev , res_sd = NULL, res_ind_blue = as.numeric(names(Dev)) < info$Year[1], label = "log-Recruitment deviations")
```

```{r, fig.cap="Time series of recruitment deviations with 95% confidence intervals. Deviations prior to the first year of the model are in blue."}
if(conv) plot_residuals(as.numeric(names(Dev)), Dev , res_sd = SE_Dev, res_ind_blue = as.numeric(names(Dev)) < info$Year[1], label = "log-Recruitment deviations")
```

### Time Series Output

```{r, fig.cap="Time series of fishing mortality."}
plot_timeseries(as.numeric(names(FMort)),FMort, label = "Fishing Mortality (F)")
```

```{r, fig.cap="Time series of F/FMSY."}
if(conv) {
  plot_timeseries(as.numeric(names(F_FMSY)),F_FMSY, label = expression(F/F[MSY]))
abline(h = 1, lty = 3)
}
```

```{r, fig.cap="Time series of spawning biomass."}
plot_timeseries(as.numeric(names(SSB)),SSB, label = "Spawning biomass")
```

```{r, fig.cap="Time series of SSB/SSBMSY."}
if(conv) {
  plot_timeseries(as.numeric(names(SSB_SSBMSY)),SSB_SSBMSY, label = expression(SSB/SSB[MSY]))
abline(h = 1, lty = 3)
}
```

```{r, fig.cap="Time series of spawning depletion."}
if(conv) {
  plot_timeseries(as.numeric(names(SSB_SSB0)),SSB_SSB0, label = expression(SSB/SSB[0]))

}
```

```{r, fig.cap="Kobe plot trajectory."}
if(conv) plot_Kobe(SSB_SSBMSY, F_FMSY, xlab = expression(SSB/SSB[MSY]), ylab = expression(F/F[MSY]))
```

```{r, fig.cap="Time series of recruitment."}
plot_timeseries(as.numeric(names(R)),R, label = "Recruitment (R)")


```

```{r, fig.cap="Time series of abundance."}
plot_timeseries(as.numeric(names(N)),N, label = "Abundance (N)")


```

```{r, fig.cap="Abundance-at-age bubble plot."}
plot_composition(c(info$Year, max(info$Year)+1), N_at_age, CAL_bins = NULL, ages = NULL, plot_type = "bubble_data")
```

```{r, fig.cap="Predicted catch-at-age bubble plot."}
plot_composition(info$Year, C_at_age, CAL_bins = NULL, ages = NULL, plot_type = "bubble_data")
```

```{r, fig.cap="Predicted catch-at-length bubble plot."}
plot_composition(info$Year, TMB_report$CALpred, CAL_bins = info$data$LenMids, plot_type = "bubble_data")
```

```{r, fig.cap="Observed (black) and predicted (red) mean age of the composition data."}
if(any(info$data$CAA_n > 0)) plot_composition(info$Year, Obs_C_at_age, C_at_age, plot_type = "mean")
```

```{r, fig.cap="Observed (black) and predicted (red) mean length of the composition data."}
if(any(info$data$CAL_n > 0)) plot_composition(info$Year, info$data$CAL_hist, TMB_report$CALpred,
                                              CAL_bins = info$data$LenMids, plot_type = "mean")
```

### Productivity
```{r fig.cap="Stock-recruit relationship."}
Arec <- TMB_report$Arec
Brec <- TMB_report$Brec
SSB <- SSB[1:(length(SSB)-1)]
if(info$data$SR_type == "BH") expectedR <- Arec * SSB / (1 + Brec * SSB) else {
  expectedR <- Arec * SSB * exp(-Brec * SSB)
}
estR <- R[as.numeric(names(R)) > info$Year[1]]
plot_SR(SSB, expectedR, rec_dev = estR, R0 = R0, S0 = SSB0, ylab = "Recruitment", trajectory = FALSE)
```

```{r fig.cap="Stock-recruit relationship (trajectory plot)."}
plot_SR(SSB, expectedR, rec_dev = estR, R0 = R0, S0 = SSB0, ylab = "Recruitment", trajectory = TRUE)
```

```{r, fig.cap="Yield plot relative to fishing mortality."}
if(conv) plot_yield_SCA_GTG(info$data, TMB_report, FMSY, MSY, xaxis = "F")
```

```{r, fig.cap="Yield plot relative to depletion."}
if(conv) yield_fn <- plot_yield_SCA_GTG(info$data, TMB_report, FMSY, MSY, xaxis = "Depletion")
```

```{r, fig.cap="Comparison of historical surplus production and estimated yield curve."}
if(conv) plot_surplus_production(B, B0 = B0, Catch, yield_fn = yield_fn)
```



